---
title: "Project"
output:
  pdf_document: default
  html_document: default
date: "2023-10-09"
---
### 1. Setting up
```{r setup, include=FALSE}
library(GISTools)
library(raster)
library(tmap)
library(rgdal) 
library(maptools) 
library(sp)
library(sf)
library(tidyverse)
library(rgeos)
library(ggplot2)
library(psych)
library(spatstat)
library(spdep)
library(jsonlite)
library(dplyr)
library(osmdata)
```

### 2. Loading Data
```{r data loading, include=FALSE}

# 2.1 Basemap - Singapore Subzones (Polygons Vectors)
subzones <- st_read(dsn = "dataset/basemap", layer = "MP14_SUBZONE_NO_SEA_PL")
base_map <- st_read(dsn = "dataset/basemap", layer = "SGP_adm0")
base_map <- base_map %>% select(ISO)
base_map <- st_transform(base_map, crs=st_crs(subzones))

# 2.2 Nightlife (Bars + Clubs) Data (Points Vectors)
query <- opq(bbox = "singapore, singapore") %>% 
  add_osm_feature(key = "amenity", value = c("bar","biergarten", "pub", "nightclub"))
rawdata_nightlife <- osmdata_sf(query)
nightlife_points <- rawdata_nightlife$osm_points %>% drop_na(name) %>%
  dplyr::select(name, amenity, `addr:postcode`, `addr:street`) 
nightlife_plg <- rawdata_nightlife$osm_polygons %>% drop_na(name) %>%
  dplyr::select(name, amenity, `addr:postcode`, `addr:street`) %>%
  st_centroid()
nightlife <- rbind(nightlife_points, nightlife_plg)

# 2.3 Midnight Restaurants Crowd Density Data
rawdata_restaurants <- read.csv("dataset/besttime/restaurants.csv")
# Restaurant DataFrame: lat, lng, name of restaurant, is_midnight, crowd density on fri and sat
restaurants <- rawdata_restaurants %>% dplyr::select(name, lat, lon, midnight_restaurant, fri_cd, sat_cd)
restaurants_coordinates <- cbind(restaurants$lon, restaurants$lat)

# 2.4 Population - Youth Data (Points Vectors)
population <- read.csv("dataset/filteredSG_population_density.csv")
yth_data <- read.csv("dataset/filteredSG_population_density.csv") %>% dplyr::select(longitude, latitude, youth)
coordinates(population) <- ~longitude+latitude

# 2.5 HDB Data (Points Vectors)
hdb <- read.csv("dataset/hdb.csv") %>% mutate(addr = paste(blk_no,street)) %>% dplyr::select(addr,lat,lng)

# 2.6 Bus Stops Data (Points Vectors)
bus_data <- data.frame()
for(i in 0:10) {
  file_name <- paste0("dataset/busstops/response(", i, ").json")
  # Handle the case for response.json (without the index)
  if(i == 0) {
    file_name <- "dataset/busstops/response.json"
  }
  json_read <- fromJSON(file_name, flatten = TRUE)
  bus_data <- rbind(bus_data, json_read$value)
}

#2.7 Grab food outlets (Points Vectors)

food_outlets <- read.csv("dataset/grab.csv")
coordinates(food_outlets) <- ~lon + lat

```

### 3. Transforming to Spatial Data

```{r data transformation}
# 3.1 Nightlife Locations

# Create a Nightlife Spatial Points DataFrame
nightlife_sf <- st_transform(nightlife, crs=st_crs(subzones)) # project to basemap's CRS
nightlife_sf <- st_intersection(nightlife_sf, base_map) # remove extra points

# Convert to Nightlife Point Pattern dataset
nightlife_ppp <- as.ppp(nightlife_sf)

# Combine with subzones for Nightlife Density DataFrame
nightlife_subzone <- st_join(subzones, nightlife_sf)
nightlife_density_subzone <- nightlife_subzone %>%
  group_by(SUBZONE_N) %>%
  summarize(nightlife_density = sum(!is.na(name)))


# 3.2 Midnight Restaurants

# Create a Restaurants Spatial Points DataFrame
restaurants_sp_data <- SpatialPointsDataFrame(restaurants_coordinates, data = data.frame(restaurants), proj4string = CRS("+proj=longlat +datum=WGS84"))
restaurants_sf <- st_as_sf(restaurants_sp_data)
restaurants_sf <- st_transform(restaurants_sf, crs = st_crs(subzones)) # project to basemap's CRS

# Convert to Restaurants Point Pattern dataset
restaurants_ppp <- as.ppp(restaurants_sf)

# Combine with subzones for Restaurants Density DataFrame
restaurants_subzone <- st_join(subzones, restaurants_sf)
restaurants_density_subzone <- restaurants_subzone %>%
  group_by(SUBZONE_N) %>%
  summarize(restaurants_density = sum(!is.na(name)))

# 3.3 Population - Youth Density

# Create a Population Raster Dataset
r <- raster(extent(population), resolution=c(0.001, 0.001)) # Here 0.001 is an example resolution. Adjust as necessary.
under5_raster <- rasterize(population, r, field="under5", fun=mean)

# Convert to Population Point Pattern dataset
ppp_data <- as.ppp(population)

# Create a Youth Spatial Polygon DataFrame
yth_sf <- st_as_sf(yth_data, coords = c("longitude", "latitude"), crs = 4326)
yth_sf <- st_transform(yth_sf, crs = st_crs(subzones)) # project to basemap's CRS

# 3.4 HDB


# 3.5 Bus Stops
bus_sf <- st_as_sf(bus_data, coords = c("Longitude", "Latitude"), crs = 4326)
bus_sf <- st_transform(bus_sf, crs = st_crs(subzones)) # project to basemap's CRS


```


### 3* ESDA - Dataset Visualization Nightlife
```{r spatial operations}

tmap_mode('plot')
tmap_options(check.and.fix = TRUE)

# Create Singapore map with nightlife location distribution
tm_shape(base_map) + tm_borders(col='black') + tm_fill(col = "orange") +
  tm_shape(nightlife_sf) + tm_dots(size = 0.0075, col = "black") + # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))

# Create Singapore map with food outlets location distribution
tm_shape(base_map) + tm_borders(col='black') + tm_fill(col = "orange") +
  tm_shape(food_outlets) + tm_dots(size = 0.0075, col = "black") + # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Grab food outlets across Singapore",
            title.position = c('left', 'bottom'))

# Create Singapore map with food outlets and nightlife location distribution
tm_shape(base_map) + tm_borders(col='black') + tm_fill(col = "orange") +
  tm_shape(food_outlets) + tm_dots(size = 0.0075, col = "red") +
  tm_shape(nightlife_sf) + tm_dots(size = 0.0075, col = "black") +
   # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Grab food outlets across Singapore",
            title.position = c('left', 'bottom'))

tmap_mode('view')
# Create Singapore map with food outlets & nightlife location distribution + bus stops
tm_shape(base_map) + tm_borders(col='black') + tm_fill(col = "orange") +
  tm_shape(bus_sf) + tm_symbols(size = 0.0075, col = "darkgreen", shape =21) +
  tm_shape(food_outlets) + tm_dots(size = 0.0075, col = "red") +
  tm_shape(nightlife_sf) + tm_dots(size = 0.0125, col = "black") +
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Grab food outlets across Singapore",
            title.position = c('left', 'bottom'))


```


### 4. Analysis on Distribution of Nightlife location in Singapore
```{r spatial operations}
tmap_mode('plot')
tmap_options(check.and.fix = TRUE)
# Local Density - Quadrat

tm_shape(base_map) + tm_borders(col='black') + 
  tm_shape(nightlife_sf) + tm_dots(size = 0.0075, col = "red") + # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))

# Quadrat density central area

central_plg <- subzones %>% filter(PLN_AREA_C %in% c("DT", "SR", "RC", "OT") | SUBZONE_N %in% c("LAVENDER"))

nightlife_filtered_sf <- st_intersection(nightlife_sf, central_plg)
restaurant_filtered_sf <- st_intersection(restaurants_sf, central_plg)

midnight_restaurant_filtered_sf <- restaurant_filtered_sf %>% filter(midnight_restaurant == 'True')

tm_shape(central_plg) + tm_borders(col='black') + 
  tm_shape(nightlife_filtered_sf) + tm_dots(size = 0.0075, col = "red") + # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))

# Density graph of the central area
tm_shape(central_plg) + tm_borders(col='black') + 
  tm_shape(nightlife_density_subzone) + tm_polygons(col = "nightlife_density") + 
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.3,
            title="Nightlife density in central area",
            title.position = c('left', 'bottom')) +
  tm_text("SUBZONE_N", size = 0.25)

tm_shape(central_plg) + tm_borders(col='black') + 
  tm_shape(restaurants_density_subzone) + tm_polygons(col = "restaurants_density") + 
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.3,
            title="Restaurant density in central area",
            title.position = c('left', 'bottom')) +
  tm_text("SUBZONE_N", size = 0.25)


# Location of restaurants on nightlife density

tm_shape(central_plg) + tm_borders(col='black') +
  tm_shape(nightlife_density_subzone) + tm_polygons(col = "nightlife_density") + 
  tm_text("SUBZONE_N", size = 0.25)+
  tm_shape(restaurant_filtered_sf) + tm_dots(size = 0.0075, col = "black") +
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.3,
            title="Restaurants location on nightlife density in central area",
            title.position = c('left', 'bottom')) 


# Local Density - By Subzone
tm_shape(base_map) + tm_borders(col='black') + tm_text("SUBZONE_N", size = 1)
  tm_shape(nightlife_density_subzone) + tm_polygons(col = "nightlife_density") + 
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))

  
  
# k function -- TBC
plot(restaurant_filtered_sf)


# KDE - use nightlife_ppp here -- IN WORK

# Apply 2D Kernel Density Estimation
kde_result <- kde2d(restaurants_ppp$x,restaurants_ppp$y, n = 50)

# Plot the original spatial data and the 2D KDE estimate
plot(restaurants_ppp, main = "2D Kernel Density Estimation", pch = 20, col = "lightblue")
contour(kde_result, add = TRUE, col = "red", lwd = 2)


# Alternative version for KDE

choose_bw <- function(spdf) {
X <- coordinates(spdf)
sigma <- c(sd(X[,1]),sd(X[,2])) * (2 / (3 * nrow(X))) ^ (1/6)
return(sigma/1000)
}

#Use a deprecated function from Github repository
install.packages("remotes")
remotes::install_github("mtennekes/oldtmaptools")
library(oldtmaptools)

coordinates(nightlife_filtered_sf) <- ~geometry 
nightlife_dens <- smooth_map(nightlife_sf,cover=blocks, bandwidth = choose_bw(nightlife_sf))
tm_shape(nightlife_dens$raster) + tm_raster()




# Quadrat analysis - hexagons and squares -- NOT WORKING YET

hexbin_map <- function(spdf, ...) {
  coordinates <- if (inherits(spdf, "sf")) st_coordinates(spdf) else coordinates(spdf)
  hbins <- fMultivar::hexBinning(coordinates, ...)
  #hbins <- fMultivar::hexBinning(coordinates(spdf),...)
  
  
  # Hex binning code block
  # Set up the hexagons to plot, as polygons
  u <- c(1, 0, -1, -1, 0, 1)
  u <- u * min(diff(unique(sort(hbins$x))))
  v <- c(1,2,1,-1,-2,-1)
  v <- v * min(diff(unique(sort(hbins$y))))/3
  # Construct each polygon in the sp model
  hexes_list <- vector(length(hbins$x),mode="list")
  for (i in 1:length(hbins$x)) {
    pol <- Polygon(cbind(u + hbins$x[i], v + hbins$y[i]),hole=FALSE)
    hexes_list[[i]] <- Polygons(list(pol),i) }
  # Build the spatial polygons data frame
  hex_cover_sp <- SpatialPolygons(hexes_list,proj4string=CRS(proj4string(spdf)))
  hex_cover <- SpatialPolygonsDataFrame(hex_cover_sp,
  data.frame(z=hbins$z),match.ID=FALSE)
  # Return the result
  return(hex_cover)
}

nightlife_hex <- hexbin_map(restaurants_density_subzone,bins=20)
tm_shape(nightlife_hex) + tm_fill(col="z",title="Count",alpha=0.7)

# Create a square grid covering the basemap
grid_size <- 0.02  # Adjust the grid size as needed
grid <- st_make_grid(base_map, cellsize = c(grid_size, grid_size), square = TRUE)

# Perform quadrat local density analysis for restaurants
restaurants_density_grid <- st_join(grid, restaurants_sf) %>%
  group_by(cell) %>%
  summarize(restaurants_density = sum(!is.na(name)))

# Visualize the results
tmap_options(check.and.fix = TRUE)

tm_shape(base_map) + 
  tm_borders(col = 'black') +
  tm_shape(restaurants_density_grid) +
  tm_fill(col = 'restaurants_density', palette = 'viridis') +
  tm_borders(col = 'white') +
  tm_layout(legend.position = c('left', 'bottom'),
            legend.text.size = 0.5,
            legend.title.size = 0.7,
            title = 'Restaurants Density in Quadrats',
            title.position = c('left', 'bottom'))

# simple grid creation attempt 


grid_size <- 1  # Adjust the grid size as needed
grid <- st_make_grid(restaurant_filtered_sf, cellsize = c(grid_size, grid_size), square = TRUE)

restaurants_density_grid <- st_join(grid, restaurant_filtered_sf) %>%
  group_by(cell) %>%
  summarize(restaurants_density = sum(!is.na(name)))



```

```{r central area point pattern}
central_plg <- subzones %>% filter(PLN_AREA_C %in% c("DT", "SR", "RC", "OT") | SUBZONE_N %in% c("LAVENDER"))

nightlife_filtered_sf <- st_intersection(nightlife_sf, central_plg)
restaurant_filtered_sf <- st_intersection(restaurants_sf, central_plg)

midnight_restaurant_filtered_sf <- restaurant_filtered_sf %>% filter(midnight_restaurant == 'True')

tm_shape(central_plg) + tm_borders(col='black') + 
  tm_shape(nightlife_filtered_sf) + tm_dots(col = "red") + 
  tm_shape(restaurant_filtered_sf) + tm_dots(col = "blue") +
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))



nightlife_ppp <- as.ppp(nightlife_filtered_sf)
marks(nightlife_ppp) <- "nightlife"
restaurants_ppp <- as.ppp(restaurant_filtered_sf)
marks(restaurants_ppp) <- "latenight restaurants"
P <- superimpose(nightlife_ppp, restaurants_ppp)
# hypothesis testing for the 1
nn.sim = vector()
P.r = P
for(i in 1:999){
  marks(P.r) = sample(P$marks)  # Reassign labels at random, point locations don't change
  nn.sim[i] = mean(nncross(P.r[P.r$marks == "nightlife", ] ,P.r[P.r$marks == "latenight restaurants", ])$dist)
}
hist(nn.sim,breaks=30, xlim=c(0,140))
abline(v=mean(nncross(P[P$marks == "nightlife", ] ,P[P$marks == "latenight restaurants", ])$dist),col="red")

# Compute empirical cumulative distribution
nn.sim.ecdf = ecdf(nn.sim)

# See how the original stat compares to the simulated distribution
nn.sim.ecdf(mean(nncross(P[P$marks == "nightlife", ] ,P[P$marks == "latenight restaurants", ])$dist)) 

```

As the p-value is 0, we  strong evidence that the observed data is unlikely to have occured by random chance