---
title: "Project"
output:
  pdf_document: default
  html_document: default
date: "2023-10-09"
---
### 1. Setting up
```{r setup, include=FALSE}
library(GISTools)
library(raster)
library(tmap)
library(rgdal) 
library(maptools) 
library(sp)
library(sf)
library(tidyverse)
library(rgeos)
library(ggplot2)
library(psych)
library(spatstat)
library(spdep)
library(jsonlite)
library(dplyr)
library(osmdata)
```

### 2. Loading Data
```{r data loading, include=FALSE}

# 2.1 Basemap - Singapore Subzones (Polygons Vectors)
subzones <- st_read(dsn = "dataset/basemap", layer = "MP14_SUBZONE_NO_SEA_PL")
base_map <- st_read(dsn = "dataset/basemap", layer = "SGP_adm0")
base_map <- base_map %>% select(ISO)
base_map <- st_transform(base_map, crs=st_crs(subzones))

# 2.2 Nightlife (Bars + Clubs) Data (Points Vectors)
query <- opq(bbox = "singapore, singapore") %>% 
  add_osm_feature(key = "amenity", value = c("bar","biergarten", "pub", "nightclub"))
rawdata_nightlife <- osmdata_sf(query)
nightlife_points <- rawdata_nightlife$osm_points %>% drop_na(name) %>%
  dplyr::select(name, amenity, `addr:postcode`, `addr:street`) 
nightlife_plg <- rawdata_nightlife$osm_polygons %>% drop_na(name) %>%
  dplyr::select(name, amenity, `addr:postcode`, `addr:street`) %>%
  st_centroid()
nightlife <- rbind(nightlife_points, nightlife_plg)

# 2.3 Midnight Restaurants Crowd Density Data
rawdata_restaurants <- read.csv("dataset/besttime/restaurants.csv")
# Restaurant DataFrame: lat, lng, name of restaurant, is_midnight, crowd density on fri and sat
restaurants <- rawdata_restaurants %>% dplyr::select(name, lat, lon, midnight_restaurant, fri_cd, sat_cd)
restaurants_coordinates <- cbind(restaurants$lon, restaurants$lat)

# 2.4 Population - Youth Data (Points Vectors)
population <- read.csv("dataset/filteredSG_population_density.csv")
yth_data <- read.csv("dataset/filteredSG_population_density.csv") %>% dplyr::select(longitude, latitude, youth)
coordinates(population) <- ~longitude+latitude

# 2.5 HDB Data (Points Vectors)
hdb <- read.csv("dataset/hdb.csv") %>% mutate(addr = paste(blk_no,street)) %>% dplyr::select(addr,lat,lng)

# 2.6 Bus Stops Data (Points Vectors)
bus_data <- data.frame()
for(i in 0:10) {
  file_name <- paste0("dataset/busstops/response(", i, ").json")
  # Handle the case for response.json (without the index)
  if(i == 0) {
    file_name <- "dataset/busstops/response.json"
  }
  json_read <- fromJSON(file_name, flatten = TRUE)
  bus_data <- rbind(bus_data, json_read$value)
}

```

### 3. Transforming to Spatial Data

```{r data transformation}
# 3.1 Nightlife Locations

# Create a Nightlife Spatial Points DataFrame
nightlife_sf <- st_transform(nightlife, crs=st_crs(subzones)) # project to basemap's CRS
nightlife_sf <- st_intersection(nightlife_sf, base_map) # remove extra points

# Convert to Nightlife Point Pattern dataset
nightlife_ppp <- as.ppp(nightlife_sf)

# Combine with subzones for Nightlife Density DataFrame
nightlife_subzone <- st_join(subzones, nightlife_sf)
nightlife_density_subzone <- nightlife_subzone %>%
  group_by(SUBZONE_N) %>%
  summarize(nightlife_density = sum(!is.na(name)))


# 3.2 Midnight Restaurants

# Create a Restaurants Spatial Points DataFrame
restaurants_sp_data <- SpatialPointsDataFrame(restaurants_coordinates, data = data.frame(restaurants), proj4string = CRS("+proj=longlat +datum=WGS84"))
restaurants_sf <- st_as_sf(restaurants_sp_data)
restaurants_sf <- st_transform(restaurants_sf, crs = st_crs(subzones)) # project to basemap's CRS

# Convert to Restaurants Point Pattern dataset
restaurants_ppp <- as.ppp(restaurants_sf)

# Combine with subzones for Restaurants Density DataFrame
restaurants_subzone <- st_join(subzones, restaurants_sf)
restaurants_density_subzone <- restaurants_subzone %>%
  group_by(SUBZONE_N) %>%
  summarize(restaurants_density = sum(!is.na(name)))

# 3.3 Population - Youth Density

# Create a Population Raster Dataset
r <- raster(extent(population), resolution=c(0.001, 0.001)) # Here 0.001 is an example resolution. Adjust as necessary.
under5_raster <- rasterize(population, r, field="under5", fun=mean)

# Convert to Population Point Pattern dataset
ppp_data <- as.ppp(population)

# Create a Youth Spatial Polygon DataFrame
yth_sf <- st_as_sf(yth_data, coords = c("longitude", "latitude"), crs = 4326)
yth_sf <- st_transform(yth_sf, crs = st_crs(subzones)) # project to basemap's CRS

# 3.4 HDB


# 3.5 Bus Stops
bus_sf <- st_as_sf(bus_data, coords = c("Longitude", "Latitude"), crs = 4326)
bus_sf <- st_transform(bus_sf, crs = st_crs(subzones)) # project to basemap's CRS


```

### 4. Analysis on Distribution of Nightlife location in Singapore
```{r spatial operations}
tmap_mode('plot')
tmap_options(check.and.fix = TRUE)
# Local Density - Quadrat

tm_shape(base_map) + tm_borders(col='black') + 
  tm_shape(nightlife_sf) + tm_dots(size = 0.0075, col = "red") + # Nightlife locations
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))


# Local Density - By Subzone
tm_shape(base_map) + tm_borders(col='black') + 
  tm_shape(nightlife_density_subzone) + tm_polygons(col = "nightlife_density") + 
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))
# KDE - use nightlife_ppp here




```

```{r central area point pattern}
central_plg <- subzones %>% filter(PLN_AREA_C %in% c("DT", "SR", "RC", "OT") | SUBZONE_N %in% c("LAVENDER"))

nightlife_filtered_sf <- st_intersection(nightlife_sf, central_plg)
restaurant_filtered_sf <- st_intersection(restaurants_sf, central_plg)

midnight_restaurant_filtered_sf <- restaurant_filtered_sf %>% filter(midnight_restaurant == 'True')

tm_shape(central_plg) + tm_borders(col='black') + 
  tm_shape(nightlife_filtered_sf) + tm_dots(col = "red") + 
  tm_shape(restaurant_filtered_sf) + tm_dots(col = "blue") +
  tm_scale_bar(width = 0.15) +
  tm_layout(legend.format = list(digits = 0),
            legend.position = c("left", "bottom"),
            legend.text.size = 0.25, 
            legend.title.size = 0.5,
            title="Nightlife location in Singapore",
            title.position = c('left', 'bottom'))



nightlife_ppp <- as.ppp(nightlife_filtered_sf)
marks(nightlife_ppp) <- "nightlife"
nightlife_ppp$n
restaurants_ppp <- as.ppp(restaurant_filtered_sf)
marks(restaurants_ppp) <- "restaurants"
latenight_restaurants_ppp <- as.ppp(midnight_restaurant_filtered_sf)
marks(latenight_restaurants_ppp) <- "latenight restaurants"
latenight_restaurants_ppp$n
restaurants_ppp$n
P <- superimpose(nightlife_ppp, restaurants_ppp)

# hypothesis testing for the distribution of nightlife and latenight restaurants
nn.sim = vector()
P.r = P
for(i in 1:999){
  marks(P.r) = sample(P$marks)  # Reassign labels at random, point locations don't change
  nn.sim[i] = mean(nncross(P.r[P.r$marks == "nightlife", ] ,P.r[P.r$marks == "latenight restaurants", ])$dist)
}
hist(nn.sim,breaks=30, xlim=c(0,300))
abline(v=mean(nncross(nightlife_ppp,restaurants_ppp)$dist),col="red")



nncross(restaurants_ppp,nightlife_ppp,k=1:3)


```


``` {r raster-foottraffic}
# Nightlife (Bars + Clubs) Crowd Density Data
rawdata_bars <- fromJSON("dataset/besttime/bars.json", flatten=TRUE)
rawdata_clubs <- fromJSON("dataset/besttime/clubs.json", flatten=TRUE)
relevant_columns <- c("venue_lat", "venue_lon", "venue_name", "venue_foot_traffic_forecast")
bars <- rawdata_bars$venues[relevant_columns]
clubs <- rawdata_clubs$venues[relevant_columns]
nightlife_ft <- rbind(bars, clubs)
ft <- nightlife_ft$venue_foot_traffic_forecast

for (i in 1:nrow(nightlife_ft)) {
  data = ft[[i]]
  nightlife_ft$fri_cd[i] <- ifelse(is.null(data), NA, data$day_raw[4])
  nightlife_ft$sat_cd[i] <- ifelse(is.null(data), NA, data$day_raw[5])
}
nightlife_ft <- nightlife_ft %>% select(-venue_foot_traffic_forecast)

coordinates <- cbind(nightlife_ft$venue_lon, nightlife_ft$venue_lat) 
# Convert the dataframe to a SpatialPointsDataFrame
nightlife_ft_sp <- SpatialPointsDataFrame(coordinates, data = data.frame(nightlife_ft), proj4string = CRS("+proj=longlat +datum=WGS84"))
# convert to sf 
nightlife_ft_sf <- st_as_sf(nightlife_ft_sp) 
nightlife_ft_sf <- st_transform(nightlife_ft_sf, crs=st_crs(subzones))

restaurants_ft_sf <- restaurants_sf

hours_to_select <- c(17, 18, 19, 20, 21)
for (i in 1:5) {
  new_fri_ft <- paste0("ft_fri_hour", hours_to_select[i])
  nightlife_ft_sf[[new_fri_ft]] <- sapply(nightlife_ft_sf$fri_cd, function(x) x[hours_to_select[i]])
  restaurants_ft_sf[[new_fri_ft]] <- sapply(restaurants_ft_sf$fri_cd, function(x) {
    if (x == "") {return(NA)}
    else {fromJSON(x)[hours_to_select[i]]}})
  new_sat_ft <- paste0("ft_sat_hour", hours_to_select[i])
  nightlife_ft_sf[[new_sat_ft]] <- sapply(nightlife_ft_sf$sat_cd, function(x) x[hours_to_select[i]])
  restaurants_ft_sf[[new_sat_ft]] <- sapply(restaurants_ft_sf$sat_cd, function(x) {
    if (x == "") {return(NA)}
    else {fromJSON(x)[hours_to_select[i]]}})
}
View(nightlife_ft_sf)
View(restaurants_ft_sf)
View(foottraffic_sf)

foottraffic_sf <- nightlife_ft_sf %>% select(-c(venue_lat, venue_lon, fri_cd, sat_cd)) %>% rename("name" = "venue_name") %>% mutate(type = "nightlife")


foottraffic_sf <- rbind(foottraffic_sf, restaurants_ft_sf %>% select(-c(lat, lon, fri_cd, sat_cd)) %>% mutate(type = ifelse(midnight_restaurant)))

```

As the p-value is 0, we  strong evidence that the observed distribution of nightlife locations and late-night restaurants is unlikely to have occured by random chance